---
dist: focal
language: python
python: "3.10"
os: linux
services:
  - docker
before_install:
  - echo '{"default-cgroupns-mode":"host"}' | sudo tee /etc/docker/daemon.json
  - sudo systemctl restart docker
install:
  - pip install pipenv
  - pipenv sync
env:
  jobs:
    - MOLECULE_DISTRO=debian:bullseye-slim
script:
  - pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    if: branch = main
    on_success: change
    on_failure: always
    recipients:
      - desarrollo.benders@idealista.com
