---

- name: NEO4J | Prepare
  ansible.builtin.import_tasks: prepare.yml
  tags:
    - neo4j_prepare

- name: NEO4J | Docker
  ansible.builtin.import_tasks: docker.yml
  tags:
    - neo4j_docker

- name: NEO4J | Configure
  ansible.builtin.import_tasks: config.yml
  when: neo4j_override_default_config
  tags:
    - neo4j_configure
