---

- name: neo4j | Configuring service
  systemd:
    name: neo4j
    state: "{{ neo4j_service_state }}"
    enabled: "{{ neo4j_service_enabled }}"
    daemon_reload: yes
  
- name: neo4j | Restart now if needed
  meta: flush_handlers

- name: neo4j | Wait for service listening
  wait_for:
    host: "{{ neo4j_address }}"
    port: "{{ neo4j_http_port }}"
    state: "{{ neo4j_service_state }}"
    delay: 5
    timeout: 300
  when:
    - neo4j_service_enabled == true
    - neo4j_service_state == "started"
    - neo4j_http_enabled == "true"

- name: neo4j | Waiting for neo4j service to be ready
  uri:
    url: "http://{{ neo4j_address }}:{{ neo4j_http_port }}"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 10
  delay: 20
  when:
    - neo4j_service_enabled == true
    - neo4j_service_state == "started"
    - neo4j_http_enabled == "true"
  changed_when: false