---

neo4j_docker_check: true
neo4j_image: neo4j
neo4j_version: 5.20.0
neo4j_tag: "{{ neo4j_version }}-{{ neo4j_edition }}"
neo4j_edition: community

docker_service_state: stopped
docker_service_enabled: false
docker_restart_handler_state: stopped

neo4j_docker_data_path: /tmp/neo4j/data
neo4j_docker_logs_path: /tmp/neo4j/logs
neo4j_docker_conf_path: /tmp/neo4j/conf
#neo4j_docker_user: root

# NEO4J docker
neo4j_docker_compose_file: "{{ neo4j_docker_files_path }}/docker-compose.yml"

# NEO4J docker compose template
neo4j_docker_compose_env_vars:
  - 'NEO4J_AUTH={{ neo4j_login_user.name }}/{{ neo4j_login_user.password }}'
neo4j_docker_compose_volumes:
  - '/var/run/docker.sock:/var/run/docker.sock'
  - "{{ neo4j_docker_data_path }}:/data"
  - "{{ neo4j_docker_logs_path }}:/logs"
  - "{{ neo4j_docker_conf_path }}:/conf"
  #- "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/test-config:{{ neo4j_docker_conf_path }}"

neo4j_override_default_config: true

neo4j_usage_report_enabled: false
neo4j_login_user:
  name: neo4j
  password: testtest