---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: neo4j-stretch
    hostname: neo4j
    image: idealista/jdk:11.0.6-stretch-openjdk-headless
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    tmpfs:
      - '/run'
      - '/run/lock'
    groups:
      - neo4j
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: goss
  lint:
    name: yamllint
