---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: neo4j-debian-host
    groups:
      - neo4j_group
    image: ${MOLECULE_DISTRO:-debian:bullseye-slim}
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/tmp/neo4j/data:/tmp/neo4j/data'
      - '/tmp/neo4j/logs:/tmp/neo4j/logs'
      - '/tmp/neo4j/conf:/tmp/neo4j/conf'
      # - '${MOLECULE_SCENARIO_DIRECTORY}/test-config:/var/lib/neo4j/conf'
    tmpfs:
      - '/tmp'
      - '/run'
      - '/run/lock'
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: neo4j
    purge_networks: true
provisioner:
  name: ansible
  log: true

scenario:
  name: default

verifier:
  name: ansible
